#!/usr/bin/env python3

# stdlib
import sys
import argparse
import copy

# 3rd-party
from visualization_msgs.msg import *
from dataset import LocalBotDataset
from process_dataset.src.validate_dataset import ValidateDataset

def main():    
    parser = argparse.ArgumentParser(description='Validate dataset')
    parser.add_argument('-d1', '--dataset1', type=str, required=True, help='Name of the dataset 1')
    parser.add_argument('-d2', '--dataset2', type=str, required=True, help='Name of the dataset 2')
    parser.add_argument('-md', '--merged_dataset', type=str, required=True, help='Name of the merged dataset')
    
    arglist = [x for x in sys.argv[1:] if not x.startswith('__')]
    args = vars(parser.parse_args(args=arglist))
    
    dataset1 = LocalBotDataset(path_seq=args['dataset1'])
    dataset2 = LocalBotDataset(path_seq=args['dataset2'])
    
    validate = ValidateDataset()
    
    validate.mergeDatasets(dataset1, dataset2, args['merged_dataset'])
    
    
    
    # if validate.validateDataset(validated_dataset):
    #     print(f'{Fore.GREEN} Dataset was succesfully validated into {validated_dataset.seq} {Fore.RESET}')
    # else:
    #     print(f'{Fore.RED} There was a problem in the validation! {validated_dataset.seq} {Fore.RESET}')
        
if __name__ == "__main__":
    main()



