#!/usr/bin/env python3

# stdlib
import sys
import argparse

# 3rd-party
from dataset import Dataset
from process_dataset.src.validate_dataset import ValidateDataset
from colorama import Fore

def main():    
    parser = argparse.ArgumentParser(description='Validate dataset')
    parser.add_argument('-dataset', '--dataset', type=str, required=True, help='Name of the dataset')
   
    arglist = [x for x in sys.argv[1:] if not x.startswith('__')]
    args = vars(parser.parse_args(args=arglist))
    
    dataset = Dataset(path_seq=args['dataset'])
    
    validate = ValidateDataset()
    
    if validate.validateDataset(dataset):
        print(f'{Fore.GREEN} Dataset was succesfully validated into {dataset.seq} {Fore.RESET}')
    else:
        print(f'{Fore.RED} There was a problem in the validation! {dataset.seq} {Fore.RESET}')
        
if __name__ == "__main__":
    main()



